### ISSUE TITLE
TOC太靠右边

### ISSUE THREAD

**Issue by handbye** [Liberxue/liberxue.github.io#14]
您好，文章toc太靠右边，是我浏览器的问题吗。我得缩放到70%才能正常显示。
![360 16550425112116102](https://user-images.githubusercontent.com/26617058/41079568-de2b7e56-6a54-11e8-82c9-472018a76f0c.png)

**Comment by xigrug** [comment]
确实是靠右了些

**Comment by Liberxue** [comment]
这几天我修复一下 ☆⌒(*＾-゜)v

**Comment by xigrug** [comment]
好像已经更新靠右了些，我怎么跟你同步呢？我的还是老版本

**Comment by Liberxue** [comment]
@xigrug  @handbye 已修复 [详见](https://github.com/Liberxue/liberxue.github.io/commit/6ed1ca5260a42c1897bcfbf05c83ca58538394ed)
