### ISSUE TITLE
你好，末页的切换有bug

### ISSUE THREAD

**Issue by yizhao1998** [Liberxue/liberxue.github.io#19]
是由于你的url定义的在首页为/?liberxue，而在其他页为/liberxue(page_number)?liberxue导致如果末页直接是第一页会造成404，建议更新如下：
![default](https://user-images.githubusercontent.com/35983404/44374334-49c53e80-a520-11e8-9633-3503560ca11c.png)

另：感谢作者提供这么好看的theme

**Comment by yizhao1998** [comment]
ps: 如果在第二页时，切换上一页的代码逻辑也有误，bug原因同上

**Comment by zuoleilei3253** [comment]
你好，请问下，如何在linux服务器上部署该博客网站

**Comment by yizhao1998** [comment]
> 你好，请问下，如何在linux服务器上部署该博客网站

fork 到github上，在github repository settings配置相关域名解析信息。

**Comment by Liberxue** [comment]
> 你好，请问下，如何在Linux的服务器上部署该博客网站

https://www.jekyll.com.cn/docs/installation/ @zuoleilei3253
