### ISSUE TITLE
请问首页上怎么新增栏目

### ISSUE THREAD

**Issue by xigrug** [Liberxue/liberxue.github.io#21]
现在的有首页，归档，标签，关于等，怎么新增一个栏目组？只修改_config.yml的links就可以了么？然后最多能有几个栏目组？

**Comment by Liberxue** [comment]
![image](https://user-images.githubusercontent.com/5831248/48713263-cd3f1a80-ec4a-11e8-9edd-dfd441d6a886.png)
最多应该十几个吧😄
