### ISSUE TITLE
Directory menu anchor can't locate correctly

### ISSUE THREAD

**Issue by AlexKaiqi** [Liberxue/liberxue.github.io#6]
Probably because of the fixed header(navbar). Directory menu anchor can't locate to the correct position. I tried add padding-top:80px;margin-top:-80px; But it didn't work.

**Comment by Liberxue** [comment]
Sorry, I don't know what you're talking about. Please send a picture or chrome develop tool to point out thx

**Comment by AlexKaiqi** [comment]
when clicking the menu fixed to the right, the anchor can't locate
properly. It is supposed to be right beneath the header.

​
