### ISSUE TITLE
when clicking the menu fixed to the right, the anchor can't locate properly. It is supposed to be right beneath the header.

### ISSUE THREAD

**Issue by AlexKaiqi** [Liberxue/liberxue.github.io#7]
使用目录定位时，由于<header></header>80px固定在顶部，所以不能准确定位到。我试了在<h*>标签加上padding-top：80px, margin-top: -80px. 但margin好像不管用。
![capture](https://user-images.githubusercontent.com/28744710/32422175-a4c317d2-c2d9-11e7-9c40-78ae21079887.PNG)
![capture2](https://user-images.githubusercontent.com/28744710/32422176-a5116fd6-c2d9-11e7-9397-6812f1f2a9b9.PNG)

**Comment by Liberxue** [comment]
z-index: 1030;
