### ISSUE TITLE
Why use coinhive?

### ISSUE THREAD

**Issue by Coioidea** [Liberxue/liberxue.github.io#9]
![_2018-02-08_09-52-30](https://user-images.githubusercontent.com/8223268/35951409-415a9c0c-0cb6-11e8-8b0c-d6f8ac39afcf.png)

Do you explain it to your forker?
Are they permitted by the template user?

**Comment by MaG21** [comment]
I looked and it seems luberxue's repo doesn't contain any js for mining. It seems the author uses coinhive on his website, which is perfectly acceptable.
